(()=>{
  const $=s=>document.querySelector(s), arena=$('#arena'), targetsLayer=$('#targets'), effects=$('#effects');
  const touchMode=()=>window.matchMedia('(max-width: 760px)').matches;
  const LEVELS=[
    {title:'WEN INVITE?',time:32,spawn:3700,travel:5200,max:1,scan:.86,goodRate:.30,scanName:'HIGH',threat:'1 AT A TIME',copy:'Safz rule #1: never send only “I want an invite”. Look for a concrete reason this person stands out.',badMsgs:['WEN INVITE?','ADD ME BRO','CHECK DM','SEND INVITE','SER, LET ME IN'],goodMsgs:['VALUE: ORIGINAL RESEARCH','WALLET + PNL: VERIFIED','BEST POSTS: LINKED','ALPHA: ONCHAIN PROOF']},
    {title:'PROOF OR VIBES?',time:34,spawn:2800,travel:5000,max:2,scan:.55,goodRate:.34,scanName:'MEDIUM',threat:'DOUBLE DMs',copy:'Two-part applications arrive. A confident claim is not proof—check the second line before deciding.',badMsgs:['VALUE: 100X CALLS|PROOF: TRUST ME BRO','PNL: HUGE|WALLET: PRIVATE','ALPHA: SECRET|SOURCE: CAN\'T SAY','BEST POSTS: MANY|LINKS: LATER'],goodMsgs:['VALUE: ONCHAIN RESEARCH|PROOF: WALLET + PNL LINKED','VALUE: WORKING TOOL|DEMO: LIVE','ALPHA: ORIGINAL THREAD|DATA: LINKED','BEST POSTS: LINKED|CALLS: ONCHAIN']},
    {title:'WHO KNOWS YOU?',time:36,spawn:2350,travel:4700,max:2,scan:.34,goodRate:.36,scanName:'LOW',threat:'DOUBLE TRICKS',copy:'Safz asks who knows you inside. A real, verifiable relationship counts; vague name-dropping does not.',badMsgs:['I KNOW SOMEONE INSIDE|NAME: CAN\'T SAY','SAFZ LIKED MY GM|SO WE ARE FRIENDS','MY COUSIN KNOWS A MOD|PROOF: ZERO','A MEMBER SAID MAYBE|INVITE ME TODAY'],goodMsgs:['GEMS OG REFERRAL|WORK WE BUILT: LINKED','MEMBER REFERRAL: VERIFIED|VALUE: RESEARCH','3 OG REFERENCES|CONTRIBUTIONS: LINKED','REFERRED BY A GEMS OG|WALLET: VERIFIED']},
    {title:'THE TRIPLE CHECK',time:38,spawn:1750,travel:4200,max:3,scan:.16,goodRate:.38,scanName:'LIMITED',threat:'TRIPLE DMs',copy:'Three-line applications mix real-looking signals with hidden nonsense. Judge the whole application, not one impressive word.',badMsgs:['VALUE: ALPHA THREAD|SOURCE: COPIED|WALLET: PRIVATE','BEST POSTS: 3 GMs|PNL: CROPPED|DIFFERENTIATOR: VIBES','REFERRAL: MY COUSIN|ALPHA: GUARANTEED|PROOF: LATER','TOOL: COMING SOON|WALLET: HIDDEN|INVITE: URGENT'],goodMsgs:['VALUE: DATA DASHBOARD|WALLET + PNL: VERIFIED|BEST POSTS: LINKED','ALPHA: ORIGINAL DATA|TOOL: LIVE|REFERRAL: VERIFIED','VALUE: CONTRACT AUDITS|WORK: PUBLIC|GEMS OG: VERIFIED','BEST THREADS: LINKED|CALLS: ONCHAIN|TOOL: OPEN SOURCE']},
    {title:'10–15 SPOTS',time:40,spawn:1050,travel:3500,max:4,scan:.08,goodRate:.42,scanName:'CRITICAL',threat:'FINAL MIXED WAVE',copy:'Only 10–15 people may enter each month. Strong applicants bring proof and patience; pressure and urgency earn nothing.',badMsgs:['VALUE: SECRET ALPHA|REFERRAL: MY COUSIN|PROOF: LATER','WALLET: +900%|ADDRESS: HIDDEN|INVITE: TODAY','BEST POST: VIRAL|CONTENT: COPIED|WAITED: 2 HOURS','ALPHA: TRUST ME|PNL: CROPPED|SPOT: SAVE MINE','I KNOW EVERYONE|PROOF: NONE|NO TIME TO WAIT'],goodMsgs:['VALUE: ORIGINAL RESEARCH|OG REFERRAL: VERIFIED|WALLET + POSTS: LINKED','ALPHA: ONCHAIN DATA|TOOL: LIVE|HAPPY TO WAIT','WALLET + PNL: VERIFIED|BEST POSTS: LINKED|VALUE: COMMUNITY DATA','REFERRAL: VERIFIED|CONTRIBUTIONS: PUBLIC|NO RUSH','VALUE: OPEN-SOURCE TOOL|ALPHA: ORIGINAL|PROOF: LINKED']}
  ];
  const scanGood=['PROOF VERIFIED ✓','REAL COOKER ✓','WALLET VERIFIED ✓'],scanBad=['ZERO PROOF ✕','FAKE PNL ✕','GENERIC DM ✕'];
  const ROASTS=['WEN REJECTED','NO PROOF, NO ENTRY','TOUCH GRASS','DM DENIED','VIBES ≠ ALPHA','COOKED'],SAFZ_ROASTS=['BRO BROUGHT VIBES, NOT ALPHA.','RETURN TO THE DISCORD LOBBY.','ZERO PROOF. MAXIMUM CONFIDENCE.','NOT EVEN TULIP CAN VERIFY THAT.'];
  const ui={score:$('#score'),accuracy:$('#accuracy'),combo:$('#combo'),gems:$('#gem-count'),hearts:$('#hearts'),timer:$('#timer'),heat:$('#heat-bar'),heatLabel:$('#heat-label'),rush:$('#rush-bar'),rushLabel:$('#rush-label'),level:$('#level-number'),levelTitle:$('#level-title'),tulip:$('#tulip-callout'),safz:$('#safz-callout')};
  const emptyTotals=()=>({score:0,gems:0,rejected:0,admitted:0,wrong:0,leaks:0,correct:0,decisions:0,bestCombo:0});
  const gameRole=gems=>gems>=20?'HONORARY GEM':gems>=10?'GEM':'GEMCCESS (TEMP)';
  const roleProgress=gems=>gems>=20?'MAX GAME ROLE UNLOCKED':gems>=10?`${20-gems}◆ TO HONORARY GEM`:`${10-gems}◆ TO GEM`;
  const state={running:false,paused:false,level:0,time:32,hearts:3,heat:0,overheated:false,combo:0,targets:new Map(),diamonds:new Set(),boss:null,lastSpawn:0,lastFrame:0,raf:0,sound:true,music:true,difficulty:'easy',totals:emptyTotals(),snapshot:null,levelCorrect:0,levelDecisions:0,levelGems:0,passed:false,holdTimer:0,playerX:50,playerY:0,moveX:0,moveY:0,pickup:null,shardWait:5000,rush:0};
  function levelData(){const base=LEVELS[state.level];if(state.difficulty!=='hard')return base;return {...base,spawn:Math.max(720,Math.round(base.spawn*.68)),travel:Math.max(2300,Math.round(base.travel*.78)),max:Math.min(5,base.max+1),scan:Math.max(.025,base.scan*.55),scanName:'LOW',threat:'HARD · '+base.threat}}
  let audioCtx,musicTimer,musicStep=0,endingTimer=0,endingVoiceTimer=0;
  function beep(freq=440,dur=.06,type='sine',vol=.04){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch{}}
  function laserSound(){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(920,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(170,audioCtx.currentTime+.18);g.gain.setValueAtTime(.065,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.2);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.21)}catch{}}
  function shatterSound(){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const n=Math.floor(audioCtx.sampleRate*.13),buf=audioCtx.createBuffer(1,n,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();src.buffer=buf;filter.type='highpass';filter.frequency.value=1100;g.gain.value=.1;src.connect(filter);filter.connect(g);g.connect(audioCtx.destination);src.start()}catch{}}
  function chargeSound(){beep(310,.045,'sine',.022)}
  function admitSound(){beep(680,.08,'sine',.04);setTimeout(()=>beep(920,.12,'sine',.04),75)}
  function gateHitSound(){beep(120,.2,'square',.065);setTimeout(()=>beep(78,.22,'sawtooth',.05),65)}
  function musicTone(freq,dur=.5,vol=.04,type='triangle'){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();const o=audioCtx.createOscillator(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;filter.type='lowpass';filter.frequency.value=1250;g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(vol,audioCtx.currentTime+.045);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(filter);filter.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur+.03)}catch{}}
  function musicBeat(step){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(step%4===0?155:95,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(42,audioCtx.currentTime+.13);g.gain.setValueAtTime(step%4===0?.09:.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.16);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.17)}catch{}}
  function musicHat(accent=false){if(!state.sound||!audioCtx)return;try{const n=Math.floor(audioCtx.sampleRate*.035),buf=audioCtx.createBuffer(1,n,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();src.buffer=buf;filter.type='highpass';filter.frequency.value=6800;g.gain.value=accent?.014:.008;src.connect(filter);filter.connect(g);g.connect(audioCtx.destination);src.start()}catch{}}
  function stadiumStep(){if(!state.music||!state.running){stopMusic();return}const step=musicStep++%32,bass=[73.42,73.42,87.31,87.31,98,98,82.41,82.41],lead=[293.66,0,349.23,0,440,0,392,349.23,293.66,0,261.63,293.66,349.23,0,392,0,440,0,523.25,0,440,392,349.23,0,329.63,349.23,392,0,293.66,0,261.63,0],chords=[[146.83,220,293.66],[174.61,261.63,349.23],[196,293.66,392],[164.81,246.94,329.63]];musicHat(step%4===2);if(step%8===0)musicBeat(step);if(step%4===0)musicTone(bass[Math.floor(step/4)%8],.46,.034,'triangle');if(step%8===0)chords[Math.floor(step/8)%4].forEach((note,i)=>musicTone(note,1.02,.014-i*.0014,'sine'));const phrase=lead[step];if(phrase&&(state.level>0||step%4===0))musicTone(phrase,.32,state.level>=3?.03:.025,'triangle');if(state.level===4&&step%8===4)musicTone(lead[step]||392,.24,.014,'sine')}
  function startMusic(){if(!state.music||!state.running||musicTimer)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();musicStep=0;stadiumStep();musicTimer=setInterval(stadiumStep,Math.max(118,138-state.level*4))}catch{}}
  function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=0}}
  function setCallout(who,text){ui[who].textContent=String(text).replace(/\.+$/,'');clearTimeout(setCallout[who]);setCallout[who]=setTimeout(()=>ui[who].textContent=who==='safz'?'READ BEFORE YOU FIRE':'PROOF SCAN READY',1600)}
  function accuracy(levelOnly=false){const d=levelOnly?state.levelDecisions:state.totals.decisions,c=levelOnly?state.levelCorrect:state.totals.correct;return d?Math.round(c/d*100):100}
  function updateHud(){ui.score.textContent=state.totals.score.toLocaleString();ui.accuracy.textContent=accuracy()+'%';ui.combo.textContent='x'+state.combo;ui.gems.textContent='◆ '+state.totals.gems;ui.hearts.textContent='◆ '.repeat(Math.max(0,state.hearts)).trim()||'GATE DOWN';ui.hearts.classList.toggle('danger',state.hearts<=1);ui.timer.textContent=Math.max(0,Math.ceil(state.time));ui.timer.parentElement.classList.toggle('urgent',state.time<=8);ui.heat.style.width=state.heat+'%';ui.heatLabel.textContent=state.overheated?'OVERHEATED':state.heat<20?'READY':Math.round(state.heat)+'%';ui.rush.style.width=Math.min(100,state.rush/65)+'%';ui.rushLabel.textContent=state.rush>0?'2X SCORE':'CHARGE';$('.heat-panel').classList.toggle('overheated',state.overheated);arena.classList.toggle('rush-mode',state.rush>0)}
  function updatePlayer(){const player=$('#player');player.style.left=state.playerX+'%';player.style.setProperty('--move-y',state.playerY+'px')}
  function spawnRushShard(){if(state.pickup)return;const el=document.createElement('i'),x=18+Math.random()*64;el.className='rush-shard';el.style.left=x+'%';el.style.top='24%';targetsLayer.appendChild(el);state.pickup={el,x,ttl:5200,max:5200};setCallout('tulip',touchMode()?'DRAG TO CATCH THE RUSH SHARD':'MOVE TO CATCH THE RUSH SHARD')}
  function collectRushShard(){if(!state.pickup)return;state.pickup.el.remove();state.pickup=null;state.shardWait=6500+Math.random()*2500;state.rush=6500;state.heat=0;state.overheated=false;state.totals.score+=350;setCallout('safz','CRYSTAL RUSH — DOUBLE SCORE');setCallout('tulip','LASER INSTANTLY COOLED');beep(980,.16,'sine',.07);setTimeout(()=>beep(1320,.2,'triangle',.06),90);updateHud()}
  function stepRushShard(dt){if(!state.pickup){state.shardWait-=dt;if(state.shardWait<=0)spawnRushShard();return}state.pickup.ttl-=dt;const p=1-state.pickup.ttl/state.pickup.max,y=24+56*Math.min(1,p),playerCatchY=80-state.playerY/Math.max(1,arena.clientHeight)*100;state.pickup.el.style.top=y+'%';if(Math.abs(y-playerCatchY)<12&&Math.abs(state.playerX-state.pickup.x)<10){collectRushShard();return}if(state.pickup.ttl<=0){state.pickup.el.remove();state.pickup=null;state.shardWait=4200+Math.random()*2200;setCallout('tulip','RUSH SHARD MISSED')}}
  function spawnDiamond(rect){if(state.diamonds.size>=5)return;const arenaRect=arena.getBoundingClientRect(),el=document.createElement('i'),x=rect.left+rect.width/2-arenaRect.left,y=rect.top+rect.height/2-arenaRect.top;el.className='diamond-drop';el.style.left=x+'px';el.style.top=y+'px';targetsLayer.appendChild(el);state.diamonds.add({el,x,y,ttl:5200,wobble:Math.random()*Math.PI*2})}
  function maybeDropDiamond(rect){if(Math.random()<(state.difficulty==='hard'?.76:.66))spawnDiamond(rect)}
  function collectDiamond(drop){const oldRole=gameRole(state.totals.gems);drop.el.remove();state.diamonds.delete(drop);state.totals.gems++;state.levelGems++;state.totals.score+=150;const newRole=gameRole(state.totals.gems),arenaRect=arena.getBoundingClientRect(),playerRect=$('#player').getBoundingClientRect();floatAt({left:playerRect.left,top:playerRect.top,width:playerRect.width,height:playerRect.height},'◆ DIAMOND CAUGHT +1',true);beep(1080,.11,'sine',.065);setTimeout(()=>beep(1420,.14,'triangle',.05),70);if(newRole!==oldRole){setCallout('safz','GAME ROLE UNLOCKED — '+newRole);const badge=document.createElement('b');badge.className='role-unlock';badge.textContent='◆ '+newRole+' UNLOCKED';badge.style.left=arenaRect.width/2+'px';badge.style.top=arenaRect.height*.42+'px';effects.appendChild(badge);setTimeout(()=>badge.remove(),1600)}updateHud()}
  function stepDiamonds(dt,now){const playerRect=$('#player').getBoundingClientRect();state.diamonds.forEach(drop=>{drop.ttl-=dt;drop.y+=dt*.036;drop.el.style.left=drop.x+Math.sin(now*.006+drop.wobble)*12+'px';drop.el.style.top=drop.y+'px';const r=drop.el.getBoundingClientRect(),caught=r.right>playerRect.left+playerRect.width*.18&&r.left<playerRect.right-playerRect.width*.18&&r.bottom>playerRect.top+playerRect.height*.12&&r.top<playerRect.bottom;if(caught){collectDiamond(drop);return}if(drop.ttl<=0||drop.y>arena.clientHeight-38){drop.el.classList.add('missed');setTimeout(()=>drop.el.remove(),260);state.diamonds.delete(drop)}})}
  function clearArena(){clearTimeout(state.holdTimer);state.targets.forEach(t=>t.el.remove());state.targets.clear();state.diamonds.forEach(d=>d.el.remove());state.diamonds.clear();if(state.boss?.el)state.boss.el.remove();if(state.pickup?.el)state.pickup.el.remove();state.boss=null;state.pickup=null}
  function resetGame(){cancelAnimationFrame(state.raf);stopMusic();unlockSafzVoice();clearArena();Object.assign(state,{running:false,paused:false,level:0,time:LEVELS[0].time,hearts:3,heat:0,overheated:false,combo:0,lastSpawn:0,totals:emptyTotals(),snapshot:null,levelCorrect:0,levelDecisions:0,levelGems:0,passed:false,playerX:50,playerY:0,moveX:0,moveY:0,shardWait:5000,rush:0});updatePlayer();$('#intro').classList.remove('active');$('#result').classList.remove('active');$('#pause-screen').classList.remove('active');$('#checkpoint').classList.remove('active');$('#briefing').classList.remove('active');$('#pause-toggle').textContent='PAUSE';showBriefing(false)}
  function showBriefing(retry){state.running=false;clearArena();const l=levelData();if(!retry)state.snapshot={...state.totals};else state.totals={...state.snapshot};ui.level.textContent=state.level+1;ui.levelTitle.textContent=l.title;$('#brief-level').textContent=String(state.level+1).padStart(2,'0')+' · '+state.difficulty.toUpperCase();$('#brief-title').textContent=l.title;$('#brief-copy').textContent=l.copy;$('#brief-time').textContent=l.time+'s';$('#brief-scan').textContent=l.scanName;$('#brief-threat').textContent=l.threat;$('#briefing').classList.add('active');updateHud()}
  function startLevel(){const l=levelData();$('#briefing').classList.remove('active');$('#checkpoint').classList.remove('active');Object.assign(state,{running:true,paused:false,time:l.time,hearts:state.difficulty==='hard'?2:3,heat:0,overheated:false,combo:0,lastSpawn:performance.now()-l.spawn*.55,lastFrame:performance.now(),levelCorrect:0,levelDecisions:0,levelGems:0,passed:false,boss:null,moveX:0,moveY:0,shardWait:4400+Math.random()*1800,rush:0});$('#pause-toggle').textContent='PAUSE';$('#instruction').textContent=touchMode()?(state.level===4?'DRAG · FIRE · CATCH EVERY DIAMOND':'DRAG TO MOVE · TAP TO FIRE · CATCH DIAMONDS'):(state.level===4?'DRAG · FIRE · CATCH EVERY DIAMOND':'DRAG OR USE WASD · CLICK TO FIRE · CATCH DIAMONDS');setCallout('safz',state.level===4?'FINAL WAVE — NO FREE INVITES':state.difficulty==='hard'?'HARD MODE — PROVE IT, TZOGIRL':'GATE IS YOURS, TZOGIRL');setCallout('tulip',state.level<2?'SCANNER ONLINE':'VERIFY THE PROOF');updateHud();startMusic();beep(520,.13);state.raf=requestAnimationFrame(loop)}
  function record(correct){state.levelDecisions++;state.totals.decisions++;if(correct){state.levelCorrect++;state.totals.correct++}}
  function spawnApplicant(now){const l=levelData();if(state.targets.size>=l.max)return;const good=Math.random()<l.goodRate,messages=good?l.goodMsgs:l.badMsgs,text=messages[Math.floor(Math.random()*messages.length)],lines=text.split('|'),messageHtml=lines.map(line=>`<span>${line}</span>`).join(''),variant=Math.floor(Math.random()*6),scanned=Math.random()<l.scan;const el=document.createElement('button');el.type='button';el.className=`applicant ${good?'good':'bad'} sprite-${variant} lines-${lines.length}`;el.setAttribute('aria-label',`Applicant says: ${lines.join('. ')}`);el.innerHTML=`<span class="dm-bubble">${messageHtml}</span>${scanned?`<span class="scan-tag">TULIP: ${(good?scanGood:scanBad)[Math.floor(Math.random()*3)]}</span>`:''}<span class="applicant-sprite" aria-hidden="true"></span>`;const side=Math.random()<.5?-1:1,startX=50+side*(18+Math.random()*32),duration=l.travel*(.9+Math.random()*.22),target={el,good,text,startX,born:now,duration,dead:false};const fire=e=>{e.preventDefault();e.stopPropagation();if(!state.running||target.dead||state.overheated)return;shoot(target)};el.addEventListener('pointerdown',fire);el.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();shoot(target)}});targetsLayer.appendChild(el);state.targets.set(el,target);if(scanned)setTimeout(()=>{if(state.targets.has(el))setCallout('tulip',good?'PROOF VERIFIED — LET THEM PASS!':'NO PROOF — FIRE!')},550)}
  function shoot(target){if(!state.running||target.dead||state.overheated)return;target.dead=true;laserSound();state.heat=Math.min(100,state.heat+(state.difficulty==='hard'?(state.level>=3?46:42):(state.level>=3?38:34)));if(state.heat>=100){state.overheated=true;setCallout('tulip','CRYSTAL OVERHEATED!');beep(95,.25,'sawtooth',.07);setTimeout(()=>{state.overheated=false;state.heat=58;updateHud()},1000)}laserTo(target.el);const rect=target.el.getBoundingClientRect(),roast=ROASTS[Math.floor(Math.random()*ROASTS.length)];setTimeout(()=>{burst(rect,target.good?'wrong':roast);funnyDeath(target,roast)},280);if(target.good){state.combo=0;state.hearts--;state.totals.wrong++;state.totals.score=Math.max(0,state.totals.score-500);record(false);floatAt(rect,'YOU SHOT A COOKER! −500',false);setCallout('safz','THAT ONE HAD REAL PROOF!');setCallout('tulip','WRONG TARGET!');beep(105,.23,'sawtooth',.075)}else{state.combo++;state.totals.bestCombo=Math.max(state.totals.bestCombo,state.combo);state.totals.rejected++;const multiplier=state.rush>0?2:1,points=(100+Math.min(400,state.combo*25))*multiplier;state.totals.score+=points;record(true);maybeDropDiamond(rect);floatAt(rect,(multiplier===2?'2X RUSH · ':'')+'APPLICATION REJECTED +'+points,true);setCallout('safz',state.combo>=5?'LET HER COOK.':SAFZ_ROASTS[Math.floor(Math.random()*SAFZ_ROASTS.length)]);beep(650+state.combo*28,.08,'square')}updateHud();setTimeout(()=>removeTarget(target),1100);if(state.hearts<=0)setTimeout(()=>endLevel(false),700)}
  function resolveArrival(target){if(target.dead)return;target.dead=true;const rect=target.el.getBoundingClientRect();if(target.good){target.el.classList.add('admitted');state.combo++;state.totals.bestCombo=Math.max(state.totals.bestCombo,state.combo);state.totals.admitted++;state.totals.score+=225+Math.min(275,state.combo*20);record(true);maybeDropDiamond(rect);floatAt(rect,'COOKER ADMITTED ✓',true);setCallout('safz','WELCOME TO ALPHAGEMS.');setCallout('tulip','PROOF CHECKED.');admitSound()}else{state.hearts--;state.combo=0;state.totals.leaks++;state.totals.score=Math.max(0,state.totals.score-250);record(false);floatAt(rect,'BAD DM GOT IN!',false);setCallout('safz','HOW DID THIS GUY GET IN?');gateHitSound()}updateHud();setTimeout(()=>removeTarget(target),target.good?680:50);if(state.hearts<=0)endLevel(false)}
  function removeTarget(t){state.targets.delete(t.el);t.el.remove()}
  function laserTo(el){const a=arena.getBoundingClientRect(),o=$('#gem-origin').getBoundingClientRect(),t=el.getBoundingClientRect(),x1=o.left+o.width/2-a.left,y1=o.top+o.height/2-a.top,x2=t.left+t.width/2-a.left,y2=t.top+t.height/2-a.top,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.createElement('i'),lock=document.createElement('i'),flare=document.createElement('i'),impact=document.createElement('i');beam.className='energy-beam';beam.innerHTML='<b></b><span></span>';beam.style.cssText=`left:${x1}px;top:${y1}px;width:${len}px;--angle:${angle}deg`;lock.className='target-lock';lock.style.cssText=`left:${x2}px;top:${y2}px`;flare.className='beam-flare';flare.style.cssText=`left:${x1}px;top:${y1}px`;impact.className='beam-impact';impact.style.cssText=`left:${x2}px;top:${y2}px`;effects.append(lock,flare,beam,impact);$('#player').classList.add('firing');setTimeout(()=>{beam.remove();lock.remove();flare.remove();impact.remove();$('#player').classList.remove('firing')},620)}
  function burst(rect,verdict='rejected'){const a=arena.getBoundingClientRect(),x=rect.left+rect.width/2-a.left,y=rect.top+rect.height/2-a.top,b=document.createElement('i'),ring=document.createElement('i'),stamp=document.createElement('b');b.className='burst';ring.className='shockwave';stamp.className='verdict-stamp '+(verdict==='wrong'?'wrong':'');stamp.textContent=verdict==='wrong'?'WRONG TARGET':verdict.toUpperCase();for(const el of [b,ring,stamp]){el.style.left=x+'px';el.style.top=y+'px';effects.appendChild(el)}for(let i=0;i<20;i++){const s=document.createElement('i');s.className='shard';s.style.cssText=`left:${x}px;top:${y}px;--dx:${(Math.random()-.5)*220}px;--dy:${(Math.random()-.62)*210}px;--rot:${Math.random()*760-380}deg`;effects.appendChild(s);setTimeout(()=>s.remove(),820)}arena.classList.remove('impact');void arena.offsetWidth;arena.classList.add('impact');shatterSound();setTimeout(()=>{b.remove();ring.remove();stamp.remove();arena.classList.remove('impact')},760)}
  function funnyDeath(target,roast){if(target.good){target.el.classList.add('hit');return}const styles=['death-launch','death-ash','death-paper','death-cabbage','death-confetti'],style=styles[Math.floor(Math.random()*styles.length)],rect=target.el.getBoundingClientRect();target.el.classList.add(style);const a=arena.getBoundingClientRect(),prop=document.createElement('b'),labels={"death-launch":'BYE, SER! 🚀',"death-ash":'👟  💨  👟',"death-paper":'📄 APPLICATION DENIED',"death-cabbage":'🥬 COOKED LIKE CABBAGE',"death-confetti":'📉 FAKE PNL CONFETTI'};prop.className='death-prop '+style;prop.textContent=labels[style]||roast;prop.style.left=rect.left+rect.width/2-a.left+'px';prop.style.top=rect.top+rect.height/2-a.top+'px';effects.appendChild(prop);setTimeout(()=>prop.remove(),950)}
  function floatAt(rect,text,good){const a=arena.getBoundingClientRect(),f=document.createElement('b');f.className='floating '+(good?'':'bad-news');f.textContent=text;f.style.left=rect.left+rect.width/2-a.left+'px';f.style.top=rect.top-a.top+'px';effects.appendChild(f);setTimeout(()=>f.remove(),900)}
  function loop(now){if(!state.running)return;const l=levelData(),dt=Math.min(60,now-state.lastFrame),maxY=arena.clientHeight*.32;state.lastFrame=now;state.time-=dt/1000;state.heat=Math.max(0,state.heat-dt*(state.overheated?0:.018));state.rush=Math.max(0,state.rush-dt);if(!touchMode()){state.playerX=Math.max(13,Math.min(87,state.playerX+state.moveX*dt*.052));state.playerY=Math.max(0,Math.min(maxY,state.playerY+state.moveY*dt*.045))}updatePlayer();stepRushShard(dt);stepDiamonds(dt,now);if(now-state.lastSpawn>=l.spawn){spawnApplicant(now);state.lastSpawn=now}state.targets.forEach(t=>{const p=Math.min(1,(now-t.born)/t.duration),ease=1-Math.pow(1-p,1.35),x=t.startX+(50-t.startX)*ease,y=82-53*ease,scale=1.02-.48*ease;t.el.style.setProperty('--x',x+'%');t.el.style.setProperty('--y',y+'%');t.el.style.setProperty('--scale',scale);if(p>=1)resolveArrival(t)});updateHud();if(state.time<=0){endLevel();return}state.raf=requestAnimationFrame(loop)}
  function endLevel(){if(!state.running)return;state.running=false;state.paused=false;state.moveX=0;state.moveY=0;state.rush=0;cancelAnimationFrame(state.raf);clearArena();const a=accuracy(true),clean=state.hearts>0&&a>=70;state.passed=true;updateHud();$('#pause-toggle').textContent='PAUSE';const card=$('.checkpoint-card'),role=gameRole(state.totals.gems);card.classList.toggle('fail',!clean);$('#checkpoint-label').textContent=clean?'LEVEL CLEARED':'LEVEL SURVIVED';$('#checkpoint-title').textContent=state.level===4?'ALL 5 LEVELS COMPLETE':clean?'GATE SECURED':'MESSY, BUT MOVING ON';$('#checkpoint-accuracy').textContent=a+'%';$('#checkpoint-gems').textContent=`${state.levelGems} ◆ CAUGHT`;$('#checkpoint-role').textContent=`${role} · ${roleProgress(state.totals.gems)}`;$('#checkpoint-copy').textContent=clean?(a>=90?'Safz: “Let her cook”':'Tulip: “Gate stable — keep reading”'):'The gate took damage — restart or keep hunting diamonds';$('#next-level').innerHTML=state.level===4?'WATCH ENDING <b>→</b>':'NEXT LEVEL <b>→</b>';$('#checkpoint').classList.add('active');beep(clean?780:420,.35,clean?'sine':'triangle')}
  function next(){if(state.level===4){$('#checkpoint').classList.remove('active');showEnding();return}state.level++;$('#checkpoint').classList.remove('active');showBriefing(false)}
  function victoryFanfare(){stopMusic();[392,523.25,659.25,783.99].forEach((n,i)=>setTimeout(()=>{beep(n,.38,'triangle',.07);beep(n/2,.5,'sine',.035)},i*210))}
  function unlockSafzVoice(){const voice=$('#safz-voice');if(!voice)return;try{voice.muted=true;const play=voice.play();play?.then(()=>{voice.pause();voice.currentTime=0;voice.muted=false}).catch(()=>voice.muted=false)}catch{voice.muted=false}}
  function speakSafz(){if(!state.sound)return;const clip=$('#safz-voice');if(clip){clip.currentTime=0;clip.volume=1;const play=clip.play();if(play?.catch)play.catch(speakSafzFallback);return}speakSafzFallback()}
  function speakSafzFallback(){if(!state.sound||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),wanted=['Guy','Ryan','George','David','Mark','Daniel','Alex','Male'],voice=wanted.map(n=>voices.find(v=>v.name.includes(n)&&/^en/i.test(v.lang))).find(Boolean)||voices.find(v=>/^en-(GB|US)/i.test(v.lang));const u=new SpeechSynthesisUtterance('Well done, my dear — you are a true Alpha Gems waifu');if(voice)u.voice=voice;u.lang=voice?.lang||'en-US';u.rate=.76;u.pitch=.46;u.volume=1;speechSynthesis.speak(u)}catch{}}
  function showEnding(){clearTimeout(endingTimer);clearTimeout(endingVoiceTimer);stopMusic();$('#ending-cutscene').classList.add('active');speakSafz();endingVoiceTimer=setTimeout(victoryFanfare,4300);endingTimer=setTimeout(finishEnding,8500)}
  function finishEnding(){clearTimeout(endingTimer);clearTimeout(endingVoiceTimer);$('#ending-cutscene').classList.remove('active');stopMusic();showResult()}
  function showResult(){const a=accuracy(),t=state.totals;let rank;if(a>=92&&t.wrong===0)rank='SAFZ APPROVED';else if(a>=84)rank='CRYSTAL GUARDIAN';else if(a>=76)rank='DM DESTROYER';else if(a>=68)rank='JUNIOR GATEKEEPER';else rank='GATE INTERN';$('#rank').textContent=rank;$('#final-score').textContent=t.score.toLocaleString();$('#final-gems').textContent='◆ '+t.gems;$('#final-role').textContent=gameRole(t.gems);$('#final-kills').textContent=t.rejected;$('#final-saved').textContent=t.admitted;$('#final-wrong').textContent=t.wrong;$('#final-leaks').textContent=t.leaks;$('#final-accuracy').textContent=a+'%';$('#final-combo').textContent='x'+t.bestCombo;$('#final-quote').textContent='SAFZ: “WELL DONE, MY DEAR — YOU ARE A TRUE ALPHAGEMS WAIFU”';$('#result').classList.add('active')}
  function shareX(){const t=state.totals,url=location.protocol.startsWith('http')?location.origin+location.pathname:'',text=`I completed all 5 levels of the @0xAlphaGEMs Gatekeeper Challenge 💎\n\nDiamonds: ${t.gems} ◆\nGame role: ${gameRole(t.gems)}\nSpammers rejected: ${t.rejected}\nReal cookers admitted: ${t.admitted}\nAccuracy: ${accuracy()}%\nRank: ${$('#rank').textContent}\n\nBuilt by @tzogirl${url?'\n\nPlay: '+url:''}`;window.open('https://x.com/intent/post?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')}
  function pauseGame(){if(!state.running)return;state.running=false;state.paused=true;state.moveX=0;state.moveY=0;cancelAnimationFrame(state.raf);stopMusic();$('#pause-screen').classList.add('active');$('#pause-toggle').textContent='RESUME'}
  function resumeGame(){if(!state.paused||state.time<=0)return;state.paused=false;state.running=true;state.lastFrame=performance.now();$('#pause-screen').classList.remove('active');$('#pause-toggle').textContent='PAUSE';startMusic();state.raf=requestAnimationFrame(loop)}
  let touchDrag=null;
  arena.addEventListener('pointerdown',e=>{if(!state.running||e.target.closest('.applicant,button,.overlay'))return;e.preventDefault();touchDrag={id:e.pointerId,x:e.clientX,y:e.clientY,playerX:state.playerX,playerY:state.playerY};arena.setPointerCapture?.(e.pointerId)});
  arena.addEventListener('pointermove',e=>{if(!touchDrag||e.pointerId!==touchDrag.id||!state.running)return;e.preventDefault();const maxY=arena.clientHeight*.32,dx=(e.clientX-touchDrag.x)/Math.max(1,arena.clientWidth)*120,dy=(e.clientY-touchDrag.y)*1.1;state.playerX=Math.max(13,Math.min(87,touchDrag.playerX+dx));state.playerY=Math.max(0,Math.min(maxY,touchDrag.playerY-dy));updatePlayer()});
  const stopTouchDrag=e=>{if(touchDrag&&e.pointerId===touchDrag.id)touchDrag=null};
  arena.addEventListener('pointerup',stopTouchDrag);arena.addEventListener('pointercancel',stopTouchDrag);arena.addEventListener('lostpointercapture',()=>{touchDrag=null});
  document.addEventListener('keydown',e=>{if(!state.running)return;if(e.code==='ArrowLeft'||e.code==='KeyA'){e.preventDefault();state.moveX=-1}else if(e.code==='ArrowRight'||e.code==='KeyD'){e.preventDefault();state.moveX=1}else if(e.code==='ArrowUp'||e.code==='KeyW'){e.preventDefault();state.moveY=1}else if(e.code==='ArrowDown'||e.code==='KeyS'){e.preventDefault();state.moveY=-1}});
  document.addEventListener('keyup',e=>{if((e.code==='ArrowLeft'||e.code==='KeyA')&&state.moveX<0)state.moveX=0;if((e.code==='ArrowRight'||e.code==='KeyD')&&state.moveX>0)state.moveX=0;if((e.code==='ArrowUp'||e.code==='KeyW')&&state.moveY>0)state.moveY=0;if((e.code==='ArrowDown'||e.code==='KeyS')&&state.moveY<0)state.moveY=0});
  document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{state.difficulty=button.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(option=>option.classList.toggle('active',option===button));beep(state.difficulty==='hard'?260:620,.09,'triangle')});
  $('#start').onclick=resetGame;$('#continue').onclick=startLevel;$('#next-level').onclick=next;$('#restart-from-pause').onclick=resetGame;$('#restart-from-checkpoint').onclick=resetGame;$('#replay').onclick=()=>{state.level=0;state.totals=emptyTotals();state.snapshot=null;$('#result').classList.remove('active');showBriefing(false)};$('#share-x').onclick=shareX;$('#skip-ending').onclick=finishEnding;$('#pause-toggle').onclick=()=>state.paused?resumeGame():pauseGame();$('#resume-game').onclick=resumeGame;$('#sound-toggle').onclick=()=>{state.music=!state.music;$('#sound-toggle').textContent='MUSIC '+(state.music?'ON':'OFF');if(state.music)startMusic();else stopMusic()};
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running)pauseGame()});
  updateHud();
  if(new URLSearchParams(location.search).get('ending')==='1'){$('#intro').classList.remove('active');showEnding()}
})();
